services:
  - type: web
    name: chess-app-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      sh setup_stockfish.sh  # Ensure Stockfish is installed
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    autoDeploy: true
